import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f4f4f4",
  },
  header: {
    backgroundColor: "#2f80c1",
    paddingTop: Platform.OS === 'ios' ? 50 : 20,
    paddingBottom: 20,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 15,
  },
  searchSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    margin: 15,
    borderRadius: 8,
    paddingHorizontal: 12,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: "#333",
  },
  listContainer: {
    paddingHorizontal: 15,
    paddingBottom: 100,
  },
  familyCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 15,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 2,
  },
  cardInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  iconContainer: {
    backgroundColor: "#2f80c115",
    padding: 12,
    borderRadius: 50,
    marginRight: 15,
  },
  responsibleName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  addressText: {
    fontSize: 13,
    color: "#666",
    marginTop: 3,
  },
  actionButtons: {
    flexDirection: 'row',
    borderLeftWidth: 1,
    borderLeftColor: '#eee',
    paddingLeft: 5,
  },
  iconBtn: {
    padding: 8,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "#f4f4f4",
  },
  label: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#2f80c1',
    marginBottom: 8,
    marginTop: 15,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
  pickerScroll: {
    marginTop: 5,
    marginBottom: 15,
  },
  tipoBtn: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: '#2f80c1',
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: '#fff',
  },
  tipoBtnActive: {
    backgroundColor: '#2f80c1',
  },
  tipoBtnText: {
    color: '#2f80c1',
    fontWeight: '600',
  },
  tipoBtnTextActive: {
    color: '#fff',
  },
  saveButton: {
    backgroundColor: '#2f80c1',
    padding: 18,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    backgroundColor: '#2f80c1',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
  },

  visitaContainer: {
    flex: 1,
    backgroundColor: '#f4f4f4',
  },
  visitaHeader: {
    backgroundColor: '#2f80c1',
    paddingTop: Platform.OS === 'ios' ? 60 : 30,
    paddingBottom: 24,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  visitaHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  visitaBackButton: {
    marginRight: 12,
    padding: 4,
    marginLeft: -8,
  },
  visitaTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 0.5,
  },
  visitaSubtitle: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.8,
    marginTop: 2,
  },
  visitaScrollContent: {
    padding: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  visitaLocationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9', 
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#C8E6C9',
  },
  visitaLocationText: {
    color: '#2E7D32', 
    fontSize: 13,
    fontWeight: '600',
  },
  visitaCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  visitaInputGroup: {
    marginBottom: 24,
  },
  visitaLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8A94A6',
    marginBottom: 8,
    letterSpacing: 0.8,
  },
  visitaInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    height: 52,
  },
  visitaTextInputField: {
    flex: 1,
    fontSize: 15,
    color: '#333',
    height: '100%',
  },
  visitaInputText: {
    fontSize: 15,
    color: '#333',
  },
  visitaRadioGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  visitaRadioButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#fff',
  },
  visitaRadioButtonActive: {
    borderColor: '#1b5f9e',
    backgroundColor: '#F0F4FF', 
  },
  visitaRadioText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#999',
  },
  visitaRadioTextActive: {
    color: '#1b5f9e',
  },
});